### ISSUE TITLE
회원가입 진행중 오류발견

### ISSUE THREAD

**Issue by chang-hyun** [rhqjatjr0093/Freight25#11]
앱 테스트 중 오류 발견하여 Issue로 올립니다.

오류 발생 과정은 다음과 같습니다.

두 계정은 모두 회원가입이 되어있지 않은 신규 계정에서 테스트가 이루어졌습니다.

1. 카카오 계정 1으로 로그인 및 회원가입(화주)을 진행 후 정상적으로 로그인
2. 로그아웃
3. 카카오 계정 2로 로그인 하자마자 회원가입시 자동으로 이전 데이터가 입력되어 있었음.
(화주/화물차 기사 회원가입 분기도 skip하고 바로 화주 회원가입으로 넘어갔으며, 화주부분 데이터는 카카오 계정 1 생성시 회원가입 진행했던 데이터가 그대로 들어가 있었음)

보완이 필요할 것 같습니다.

**Comment by rhqjatjr0093** [comment]
저도 한번 확인해 보겠습니다.
그런데 실제 기기에서는 하나의 기기에서 하나의 계정만 사용할테니 극단적으로는 한번의 플로우만 정상작동되면 될거같네요

**Comment by psunny0104** [comment]
앱을 새로 시작하지 않은 상태에서 입력정보가 그대로 남아있는 거면, 생명주기를 좀 알아봐야 할 것 같아요. 내일 중으로 혹시 로그인과 회원가입 흐름에서 생긴 문제는 아닌지 알아볼게요!

**Comment by rhqjatjr0093** [comment]
회원 가입 버튼을 누를 때 onpress 안에서 setState로 전부 초기화 하는 방법도 있습니다. re rendering 보다는 이걸로 해결하는게 더 빠를거같아요

**Comment by chang-hyun** [comment]
이번 이슈가 조금 극단적인 케이스같긴 합니다..
입력되있던 자료같은 경우 초기화를 통해 해결이 가능할 것 같습니다.

그런데 두번째 회원가입때 첫번째 회원가입시 선택한 회원가입 분기(화주) 그대로 들어가진부분은 혹시 해결방안이 있을까요?

**Comment by tlimkim** [comment]
초기화를 진행하면 두번째 회원가입 때 분기 그대로 안 들어가지지 않을까요?

**Comment by rhqjatjr0093** [comment]
그 부분은 제가 navigator를 나누면 해결 가능합니다 지금 스택 네비게이션이라서 분기 화면 - 첫번째 회원가입으로 선택한 화면 이렇게 쌓여있어서 그럴거에요

**Comment by rhqjatjr0093** [comment]
파일 많아지는게 싫어서 저번 커밋과 다르게 합쳐놨는데 이런 문제가 생길수도 있네요 다시 분리하겠습니다

**Comment by rhqjatjr0093** [comment]
commonAction.reset 을 이용하여 해결했습니다
