### ISSUE TITLE
Problem on overlapping between status bar and TopNavigation at iPhone X

### ISSUE THREAD

**Issue by tlimkim** [rhqjatjr0093/Freight25#2]
- 문제
iPhone X 기종에서 Notch 부분의 status bar (시간, 배터리 표시 부분)과 TopNavigation (화물 앱 이름, menu toggle 부분)이 겹치는 문제 발견.

- 해결사항
checkFreight 브랜치에서 `check.component.tsx` 파일에 ` <SafeAreaView style={{flex: 0, backgroundColor: 'white'}} />` 를 `React.Fragement` 에 추가함

- TODO
1. 안드로이드 폰에서도 checkFreight 브랜치의 '배차 확인' screen에 status bar가 잘 나오는 지 확인
2. 다른 screen component에도 적용

**Comment by psunny0104** [comment]
1. 안드로이드에서 status bar는 문제 없이 잘 표현됩니다.

2. 리액트 네이티브에서는 CSS기반이라 size의 기본 단위가 안드로이드의 dp 처럼 상대적인 단위가 아닌 것 같습니다. 그래서 반응형처럼 디스플레이 환경에 맞춰지는 게 아니라 택림이가 ios에서 실행한 화면과 다르게 안드로이드에서는 비율이 깨져서 나옵니다. 명시는 안 되어 있는데 기본 단위가 px인 것 같기도...
  리액트 네이티브에서도 CSS에서 입력한 값을 다양한 디스플레이 환경에서도 dp나 pt같은 상대적인 단위처럼 동일하게 적용될 수 있는 방법이 있는지 우선 찾아봐야 할 것 같아요. 외부 모듈이나 RN에서 자체 제공하는 해결방법이 없다면 수동으로 계산하던지, 아니면 개발 타겟을 통일해야 되나..

![image](https://user-images.githubusercontent.com/53979482/79771525-e0877580-8369-11ea-8675-afb48f69dc62.png)
**Pixel 2**
![image](https://user-images.githubusercontent.com/53979482/79771760-2fcda600-836a-11ea-9951-b5b21fdf029d.png)
**Galaxy 7 Edge**

**Comment by psunny0104** [comment]
slack noti test

**Comment by tlimkim** [comment]
@psunny0104 

> 안드로이드에서 status bar는 문제 없이 잘 표현됩니다.

Safeviewarea 없이도 잘 표시된다는거죠? 아마 이것도 기종에 따라 다를 수 있긴 해요(안드로이드 or iOS). 노치가 있는 기종에서 좀 문제가 되는 것 같더라고요.  

> 그래서 반응형처럼 디스플레이 환경에 맞춰지는 게 아니라 택림이가 ios에서 실행한 화면과 다르게 안드로이드에서는 비율이 깨져서 나옵니다.

그러네요.. 일단 언급하신 것처럼 그런 모듈이 있는지부터 찾아보는 방향으로 진행할게요. React Native 자체가 여러 기기를 타겟팅 하는건데 여러 기기에서 모두 그려지게 되는 다른 방법이 있을 것 같긴 해요.

**Comment by tlimkim** [comment]
Solution:
[https://www.npmjs.com/package/react-native-responsive-fontsize](react-native-responsive-fontsize)

여기서 보면 `RFPercentage()`를 통해 각 device에 따른 responsive 한 font size를 얻을 수 있습니다. 저희가 각자 테스트하는 device들이 다르고 device들의 display 크기도 다르기 때문에 `Stylesheet` 을 통한 fontsize 시 responsive 모듈을 이용해야 할 것 같네요.

TODO:
- screen 마다 fontsize를 `RFPercentage()` 로 변경
