### ISSUE TITLE
Problem on logout that needs to show login button

### ISSUE THREAD

**Issue by tlimkim** [rhqjatjr0093/Freight25#4]
- 문제점

현재 메인 화면에서 Top navigation의 로그아웃 버튼을 누를 때 로그아웃이 되면서 맨 처음 로고 화면으로 가지만 그곳에서 로그인 버튼이 존재하지 않음

- TODO

1. 로그아웃 후 로그인 버튼이 있는 메인 로고 화면으로 이동

**Comment by rhqjatjr0093** [comment]
main.component 화면에서 

props.navigation.navigate(AppRoute.AUTH); 함수는 단순 화면 이동 함수입니다
props.navigation.push(AppRoute.AUTH); 로 변경하면 네비게이터 자체를 리로드 하기 때문에 해결 가능합니다 커밋 했습니다
