### ISSUE TITLE
Problem on AsyncStorage of 'userType'

### ISSUE THREAD

**Issue by tlimkim** [rhqjatjr0093/Freight25#6]
문제

- 화물차 기사 or 화주에 대한 구분을 현재는 async storage로 하는 것 같은데 잘 되시나요?`AsyncStorage.setItem('userType', 'owner');`
여기서 static하게 설정 하는 것 같은데, owner로 설정을 해도 자꾸 `userType`을 화물차 기사로 인증을 하는 것 같아요 (userType에 따라 화물 조회하기, 화물 등록하기가 구분이 되지 않음). 혹시 해결중인 부분인가요?

- To reproduce

앱을 지우고 다시 실행해도 문제 반복됨

**Comment by chang-hyun** [comment]
auth.component.tsx에 있는것과 loading.tsx 모두 바꿔주면 정상작동함!
