### ISSUE TITLE
Issue on Picker of react-native

### ISSUE THREAD

**Issue by tlimkim** [rhqjatjr0093/Freight25#9]
### 문제
- react-native의 Picker 사용시, 안드로이드에서는 문제 없이 보이지만 iOS에서는 화면에 면적이 넓게 잡혀 디자인 상 깔끔해보이지 않음

- iOS (Picker)
![Screen Shot 2020-05-08 at 4 32 36 PM](https://user-images.githubusercontent.com/28242007/81382548-89471a80-9149-11ea-81a8-e1547a1384ed.png)

### 제안

iOS에서 Picker가 면적이 넓게 나오는데, 이를 줄이는 방법이 따로 없고 다른 모듈을 사용하라고 하더라구요. 그래서 저는 `react-native-picker-select` 라는 것을 사용하였는데, 안드로이드와 iOS 모두 안드로이드 형식처럼 보여줍니다.

- iOS (RNPickerSelect)
![Screen Shot 2020-05-08 at 4 38 36 PM](https://user-images.githubusercontent.com/28242007/81383066-5f422800-914a-11ea-9b3f-9cbf5ffe1da0.png)

![Screen Shot 2020-05-08 at 4 38 46 PM](https://user-images.githubusercontent.com/28242007/81383079-649f7280-914a-11ea-95e5-63c6257e3838.png)

구현하는 것은 거의 비슷하게 할 수 있습니다. 프론트분들의 의견 달아주세요
[react-native-picker-select](https://github.com/lawnstarter/react-native-picker-select)

**Comment by chang-hyun** [comment]
좋은 의견 같습니다. 

저번 UI Kitten 사용이 불가능했던 이유중 하나가 picker 내의 element가 4개 이상일 경우를 지원하지 않아서 바꿨는데 react-native-picker-select가 여러개의 element가 추가되어있어도 정상적으로 동작한다면 현재 방식보다 좋을 것으로 보입니다.

element부분만 확인해주시면 제 파트도 같은 모듈을 사용하여 수정 반영하겠습니다.

**Comment by tlimkim** [comment]
@chang-hyun 

UI Kitten이 불가능했던 이유가 값에 하나의 값 말고도 다른 information data가 들어가서 저희가 사용하지 않는 것이였죠? 
방금 `react-native-picker-select` 로 선택된 값이 담긴 변수를 log 찍어봤는데 value만 얻을 수 있습니다.

<img width="492" alt="Screen Shot 2020-05-08 at 5 04 17 PM" src="https://user-images.githubusercontent.com/28242007/81385244-fa88cc80-914d-11ea-9a8f-dc624bfd6463.png">

**Comment by chang-hyun** [comment]
@tlimkim 

string이 아닌 value가 나오며 이 value값을 string으로 처리하는데 여러 복잡한 process가 필요하다는 의견이 있었던 것으로 기억합니다. 현재에도 string값이 아닌 value만 얻을 수 있다는 말씀이신가요?

**Comment by tlimkim** [comment]
@chang-hyun 

음 string만 나오면 상관 없지 않나요?? 

<img width="879" alt="Screen Shot 2020-05-08 at 5 08 53 PM" src="https://user-images.githubusercontent.com/28242007/81385609-99adc400-914e-11ea-9bb2-21e67257355a.png">

이전에는 이런 식으로 나와서 문제가 된다고 하지 않았나요? index parsing 해야하는 작업이 생기니깐요.

**Comment by chang-hyun** [comment]
@tlimkim 

저도 한번 확인해보고 다시 답변하겠습니다.

**Comment by rhqjatjr0093** [comment]
위 처럼 value 값이 나온다면 상관없습니다. 저 모듈로 교체하는게 좋을 거 같네요

**Comment by tlimkim** [comment]
넵. 읻단 개인정보 수정 scene을 저 모듈로 만들었고,
iOS랑 안드로이드기기에서 모두 테스트 하였는데 문제 없이 동작합니다.

master에 push 해놓을게요.

**Comment by chang-hyun** [comment]
react-native-picker-select 확인해 보았는데 적용결과 style부분을 건드리지 않으면 전반적으로 UI가 좀 지저분해 보이는것 같습니다.

확인해보니 현재 UI Kitten을 이용해도 String형태로 return을 받을 수 있음을 확인했는데 그냥 UI Kitten을 쓰는게 어떨지요?

**Comment by tlimkim** [comment]
오 return값만 저렇게 받아올 수 있다면 상관 없겠죠?

@chang-hyun 혹시 값 찍어본 코드 어떻게 되나요?

**Comment by tlimkim** [comment]
그리고 @chang-hyun 

UI가 지저분해지는 이유가 아마 Layout을 넣어서 그런건데, 그거 없애면 깔끔해지지 않을까 싶어요.

제 예시 화면이 그런데, 저정도면 그냥 select를 써도 무방한 디자인일수도 있을 것 같아요

**Comment by chang-hyun** [comment]
@tlimkim 

```
const carType = [
  { text: '카고' },
  { text: '탑차' },
  { text: '냉동' },
  { text: '냉장' },
];

```
이런식으로 data type을 지정하고

```
<Select
                placeholder='타입'
                data={carType}
                selectedOption={selectedCarType}
                onSelect={setSelectedCarType}
/>

```
이런식으로 UI Kitten의 select를 사용하게 되는데 selectedCarType은 말씀하신대로
{ text: '카고' }와 같은 형태로 나옵니다.

selectedCarType.text로 접근해서 log를 찍어본 결과 제가 올린 스크린샷과 같이 string형태로 찍히는 것을 확인했습니다.

**Comment by chang-hyun** [comment]
react-native-picker-select 사용
